FROM mongo

COPY mongoScript.js mongoScript.js

# to start the container run:
# docker run --name mongo_container mongo_image:1.0

# after starting the container run: to create the DB
# docker exec -ti mongo_container mongosh localhost:27017 mongoScript.js
